-- 여기는 관리자 접속

CREATE TABLESPACE myFoodDB
DATAFILE 'C:/oraclexe/data/myFoodDB.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER myFood IDENTIFIED BY myfood
DEFAULT TABLESPACE myFoodDB;

GRANT DBA TO myFood;