DROP USER BOOKUSER CASCADE;

DROP TABLESPACE RENTBOOKDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

CREATE TABLESPACE RENTBOOKDB
DATAFILE 'C:/oraclexe/data/rentbook.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER bookuser IDENTIFIED BY bookuser
DEFAULT TABLESPACE rentbookdb;

GRANT DBA TO bookuser;